# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
#Esta línea de abajo la agregé yo.
#defaultContentLanguage: en

en:
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  disabled: false
  languageCode: en
  languageDirection: ltr
  languageName: English
  title: Personal page
  weight: 0
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
